name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build exe
        run: |
          pyinstaller --onefile ^
          --add-data "templates;templates" ^
          --add-data "static;static" ^
          manage.py

      - name: Upload exe
        uses: actions/upload-artifact@v3
        with:
          name: exe-file
          path: dist/